spring.application.name=nostracasa

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nostracasa
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
