spring.application.name=nostracasa

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.ezvtrmbqphttooiobaii
spring.datasource.password=Estoeslabasededatosdeitaliandesing
server.port=180528
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Internacionalizacion (i18n)
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
